import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { Label } from '../components/ui/label';
import { Input } from '../components/ui/input';
import { Button } from '../components/ui/button';
import { ChevronRight, UserPlus } from 'lucide-react';

/**
 * ════════════════════════════════════════════════════════════════
 * ADD EMPLOYEE PAGE  —  Route: /employees/new
 * ════════════════════════════════════════════════════════════════
 * OWNER: [YOUR FRIEND]
 * ACCESS: Admin only
 *
 * BACKEND:
 *   POST /employees?password=<initial_password>
 *   Returns: EmployeeResponse (includes id, login_id, full_name…)
 *
 * LOGIN ID: Generated by backend. Format: OI + fi(2)+la(2) + 4-digit-year + serial
 *   e.g. OIJODO2026001  — show on final step from mutation response.
 * ════════════════════════════════════════════════════════════════
 */

// ── Zod schemas per step ───────────────────────────────────────
const step1Schema = z.object({
  first_name: z.string().min(1, 'Required'),
  last_name: z.string().min(1, 'Required'),
  email: z.string().email('Valid email required'),
  date_of_joining: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Required'),
  phone: z.string().optional(),
});

const step2Schema = z.object({
  department: z.string().optional(),
  position: z.string().optional(),
  location: z.string().optional(),
  // ── Three required Private Info fields ───────────────────────
  address: z.string().optional(),           // Residing Address
  nationality: z.string().optional(),       // Nationality
  personal_email: z.string().email('Valid email').optional().or(z.literal('')),  // Personal Email
});

const step3Schema = z.object({
  password: z.string().min(8, 'Minimum 8 characters'),
  confirm_password: z.string().min(8, 'Required'),
}).refine(d => d.password === d.confirm_password, {
  message: "Passwords don't match",
  path: ['confirm_password'],
});

type Step1 = z.infer<typeof step1Schema>;
type Step2 = z.infer<typeof step2Schema>;
type Step3 = z.infer<typeof step3Schema>;

const TOTAL_STEPS = 4;

export function AddEmployeePage() {
  const [step, setStep] = useState(1);
  const [s1Data, setS1Data] = useState<Step1 | null>(null);
  const [s2Data, setS2Data] = useState<Step2 | null>(null);
  const [createdEmployee, setCreatedEmployee] = useState<{ id: number; login_id: string; full_name: string } | null>(null);

  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const form1 = useForm<Step1>({ resolver: zodResolver(step1Schema) });
  const form2 = useForm<Step2>({ resolver: zodResolver(step2Schema) });
  const form3 = useForm<Step3>({ resolver: zodResolver(step3Schema) });

  const mutation = useMutation({
    mutationFn: async ({ payload, password }: { payload: object; password: string }) => {
      const res = await api.post(`/employees?password=${encodeURIComponent(password)}`, payload);
      return res.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['employees'] });
      setCreatedEmployee({
        id: data.id,
        login_id: data.login_id ?? data.user?.login_id ?? '—',
        full_name: data.full_name,
      });
      setStep(4);
    },
  });

  const onStep1Next = form1.handleSubmit((data) => { setS1Data(data); setStep(2); });
  const onStep2Next = form2.handleSubmit((data) => { setS2Data(data); setStep(3); });
  const onStep3Submit = form3.handleSubmit((data) => {
    if (!s1Data || !s2Data) return;
    const payload = {
      ...s1Data,
      ...Object.fromEntries(Object.entries(s2Data).filter(([, v]) => v !== '' && v !== undefined)),
      phone: s1Data.phone || undefined,
    };
    mutation.mutate({ payload, password: data.password });
  });

  const Field = ({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) => (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      {children}
      {error && <p className="text-xs text-[#EB5757]">{error}</p>}
    </div>
  );

  return (
    <div className="w-full max-w-2xl mx-auto animate-in fade-in duration-300">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-foreground tracking-tight mb-1">Add Employee</h1>
        <p className="text-sm text-muted-foreground">Create a new employee account and profile.</p>
      </div>

      {/* Step indicator */}
      <div className="flex items-center gap-2 mb-8">
        {Array.from({ length: TOTAL_STEPS }).map((_, i) => (
          <React.Fragment key={i}>
            <div className={`flex items-center justify-center w-8 h-8 rounded-full text-sm font-semibold transition-colors ${
              i + 1 <= step ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'
            }`}>
              {i + 1}
            </div>
            {i < TOTAL_STEPS - 1 && (
              <div className={`flex-1 h-0.5 transition-colors ${i + 1 < step ? 'bg-primary' : 'bg-border'}`} />
            )}
          </React.Fragment>
        ))}
      </div>

      <div className="bg-card border rounded-xl p-8 shadow-sm">

        {/* ── STEP 1: Basic Info ── */}
        {step === 1 && (
          <form onSubmit={onStep1Next} className="space-y-5">
            <h2 className="text-lg font-semibold">Basic Information</h2>
            <div className="grid grid-cols-2 gap-4">
              <Field label="First Name" error={form1.formState.errors.first_name?.message}>
                <Input placeholder="John" {...form1.register('first_name')} />
              </Field>
              <Field label="Last Name" error={form1.formState.errors.last_name?.message}>
                <Input placeholder="Doe" {...form1.register('last_name')} />
              </Field>
            </div>
            <Field label="Work Email" error={form1.formState.errors.email?.message}>
              <Input type="email" placeholder="john@company.com" {...form1.register('email')} />
            </Field>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Date of Joining" error={form1.formState.errors.date_of_joining?.message}>
                <Input type="date" {...form1.register('date_of_joining')} />
              </Field>
              <Field label="Phone (Optional)">
                <Input type="tel" placeholder="+91 98765 43210" {...form1.register('phone')} />
              </Field>
            </div>
            <div className="flex justify-end mt-8 pt-6 border-t">
              <Button type="submit">Next <ChevronRight className="h-4 w-4 ml-1" /></Button>
            </div>
          </form>
        )}

        {/* ── STEP 2: Job Details + Private Fields ── */}
        {step === 2 && (
          <form onSubmit={onStep2Next} className="space-y-5">
            <h2 className="text-lg font-semibold">Job Details</h2>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Department">
                <Input placeholder="Engineering" {...form2.register('department')} />
              </Field>
              <Field label="Position">
                <Input placeholder="Software Engineer" {...form2.register('position')} />
              </Field>
            </div>
            <Field label="Work Location">
              <Input placeholder="Bengaluru" {...form2.register('location')} />
            </Field>

            <div className="pt-2 border-t">
              <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4">Private Info</h3>
              <div className="space-y-4">
                <Field label="Residing Address" error={form2.formState.errors.address?.message}>
                  <Input placeholder="123 Main St, Bengaluru 560001" {...form2.register('address')} />
                </Field>
                <div className="grid grid-cols-2 gap-4">
                  <Field label="Nationality" error={form2.formState.errors.nationality?.message}>
                    <Input placeholder="Indian" {...form2.register('nationality')} />
                  </Field>
                  <Field label="Personal Email" error={form2.formState.errors.personal_email?.message}>
                    <Input type="email" placeholder="john@gmail.com" {...form2.register('personal_email')} />
                  </Field>
                </div>
              </div>
            </div>

            <div className="flex justify-between mt-8 pt-6 border-t">
              <Button type="button" variant="outline" onClick={() => setStep(1)}>Back</Button>
              <Button type="submit">Next <ChevronRight className="h-4 w-4 ml-1" /></Button>
            </div>
          </form>
        )}

        {/* ── STEP 3: Password ── */}
        {step === 3 && (
          <form onSubmit={onStep3Submit} className="space-y-5">
            <h2 className="text-lg font-semibold">Set Initial Password</h2>
            <p className="text-sm text-muted-foreground">
              The employee will use this password to log in for the first time. They can change it afterward.
            </p>
            <Field label="Initial Password" error={form3.formState.errors.password?.message}>
              <Input type="password" placeholder="Min 8 characters" {...form3.register('password')} />
            </Field>
            <Field label="Confirm Password" error={form3.formState.errors.confirm_password?.message}>
              <Input type="password" placeholder="Repeat password" {...form3.register('confirm_password')} />
            </Field>
            {mutation.isError && (
              <p className="text-sm text-[#EB5757] bg-[#EB5757]/10 px-3 py-2 rounded-md">
                {(mutation.error as any)?.response?.data?.detail ?? 'Failed to create employee. Please try again.'}
              </p>
            )}
            <div className="flex justify-between mt-8 pt-6 border-t">
              <Button type="button" variant="outline" onClick={() => setStep(2)}>Back</Button>
              <Button type="submit" disabled={mutation.isPending}>
                {mutation.isPending ? 'Creating...' : 'Create Employee'}
              </Button>
            </div>
          </form>
        )}

        {/* ── STEP 4: Success ── */}
        {step === 4 && createdEmployee && (
          <div className="text-center space-y-4 py-6">
            <div className="h-14 w-14 rounded-full bg-[#27AE60]/10 flex items-center justify-center mx-auto">
              <UserPlus className="h-7 w-7 text-[#27AE60]" />
            </div>
            <h2 className="text-lg font-semibold">Employee Created!</h2>
            <p className="text-sm text-muted-foreground">
              <span className="font-medium text-foreground">{createdEmployee.full_name}</span> has been added to your organization.
            </p>
            <p className="text-sm text-muted-foreground">Their system Login ID is:</p>
            <div className="bg-secondary rounded-lg px-4 py-2 inline-block font-mono text-lg font-bold text-primary">
              {createdEmployee.login_id}
            </div>
            <p className="text-xs text-muted-foreground">
              Share this ID and the initial password with the employee.
            </p>
            <div className="flex gap-3 justify-center pt-4">
              <Button variant="outline" onClick={() => navigate('/employees')}>
                Back to Directory
              </Button>
              <Button onClick={() => navigate(`/employees/${createdEmployee.id}`)}>
                View Profile
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
